
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    #续约更新时间间隔
    lease-expiration-duration-in-seconds: 10
server:
  port: 8096

zuul:
  routes:
    api-a:
        path: /api-a/**
        serviceId: SERVICE-RIBBON
    api-b:
        path: /api-b/**
        serviceId: FEIGN-CLINET