server:
  port: 8094

spring:
  application:
    name: service-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    #续约更新时间间隔
    lease-expiration-duration-in-seconds: 10